spring:
  application:
    name: config
  profiles:
    active: native # native, search locations? ???? ??? native? ???? ??.
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        native:
          search-locations:
            - file:///C:/Users/Desiree/IdeaProjects/msa/setting
            - file:///C:/Users/Desiree/IdeaProjects/msa/setting/{application}

server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

encrypt:
  key: mySecretKey
